/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "add.h"
#include <time.h>

int *
get_addition_1_svc(int *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

time_t *
get_time_1_svc(void *argp, struct svc_req *rqstp)
{
	static time_t  result;

	/*
	 * insert server code here
	 */

    *result = time(NULL)

	return &result;
}
