/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "add.h"
#include <time.h>


void
add_prog_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	int  get_addition_1_arg;
	time_t  *result_2;
	char *get_time_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, ADD_PROG, ADDS_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = get_addition_1(&get_addition_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = get_time_1((void*)&get_time_1_arg, clnt);
	if (result_2 == (time_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}else{
        printf(ctime(result_2));
        
    }
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	add_prog_1 (host);
exit (0);
}
