/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MY_RPC_H_RPCGEN
#define _MY_RPC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXNAMELEN 255

typedef char *nametype;

typedef struct namenode *namelist;

struct namenode {
	nametype name;
	namelist next;
};
typedef struct namenode namenode;

struct readdir_res {
	int errno;
	union {
		namelist list;
	} readdir_res_u;
};
typedef struct readdir_res readdir_res;

typedef struct intnode *intlist;

struct intnode {
	int v;
	intlist next;
};
typedef struct intnode intnode;

struct coupled_int_list {
	intlist a;
	intlist b;
};
typedef struct coupled_int_list coupled_int_list;

struct coupled_matrix {
	struct {
		u_int a_len;
		int *a_val;
	} a;
	struct {
		u_int b_len;
		int *b_val;
	} b;
	int d1;
	int d2;
};
typedef struct coupled_matrix coupled_matrix;

#define CLOCKPROG 0x31111111
#define MYVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define GETTIME 1
extern  char ** gettime_1(void *, CLIENT *);
extern  char ** gettime_1_svc(void *, struct svc_req *);
#define MERGE 2
extern  intlist * merge_1(coupled_int_list *, CLIENT *);
extern  intlist * merge_1_svc(coupled_int_list *, struct svc_req *);
#define REVERSE 3
extern  char ** reverse_1(char **, CLIENT *);
extern  char ** reverse_1_svc(char **, struct svc_req *);
#define READDIR 4
extern  readdir_res * readdir_1(nametype *, CLIENT *);
extern  readdir_res * readdir_1_svc(nametype *, struct svc_req *);
#define ADDMATRIX 5
extern  int * addmatrix_1(coupled_matrix *, CLIENT *);
extern  int * addmatrix_1_svc(coupled_matrix *, struct svc_req *);
extern int clockprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define GETTIME 1
extern  char ** gettime_1();
extern  char ** gettime_1_svc();
#define MERGE 2
extern  intlist * merge_1();
extern  intlist * merge_1_svc();
#define REVERSE 3
extern  char ** reverse_1();
extern  char ** reverse_1_svc();
#define READDIR 4
extern  readdir_res * readdir_1();
extern  readdir_res * readdir_1_svc();
#define ADDMATRIX 5
extern  int * addmatrix_1();
extern  int * addmatrix_1_svc();
extern int clockprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_nametype (XDR *, nametype*);
extern  bool_t xdr_namelist (XDR *, namelist*);
extern  bool_t xdr_namenode (XDR *, namenode*);
extern  bool_t xdr_readdir_res (XDR *, readdir_res*);
extern  bool_t xdr_intlist (XDR *, intlist*);
extern  bool_t xdr_intnode (XDR *, intnode*);
extern  bool_t xdr_coupled_int_list (XDR *, coupled_int_list*);
extern  bool_t xdr_coupled_matrix (XDR *, coupled_matrix*);

#else /* K&R C */
extern bool_t xdr_nametype ();
extern bool_t xdr_namelist ();
extern bool_t xdr_namenode ();
extern bool_t xdr_readdir_res ();
extern bool_t xdr_intlist ();
extern bool_t xdr_intnode ();
extern bool_t xdr_coupled_int_list ();
extern bool_t xdr_coupled_matrix ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_MY_RPC_H_RPCGEN */
