/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "my_rpc.h"
#include <stdio.h>


void print_list(intlist l){
    intlist p;

    printf("\t");
    for(p = l; p!=NULL; p = p->next)
        printf("%d ", p->v);
    printf("\n");
}


/*
 * print matrix content
 * input:
 *  p, address of matrix
 *  d1, d2, dimensions of matrix
 */
void print_matrix(int *p, int d1, int d2){
    int i, j;
    int index = 0;
   
    for(i = 0; i<d1; i++){
        printf("\t");
        for(j = 0; j< d2; j++){
            printf("%d\t",c[index++]);
        }
        printf("\n");
    }
}

        

intlist generate_list(int *a, int size){
    intlist head = NULL;
    int i;
    for(i = 0; i< size; i++){
        intlist tmp = (intlist)malloc(sizeof(intnode));
        tmp->v = a[i];
        tmp->next = head;
        head = tmp;
    }  
    return head;
}

void
clockprog_1(char *host)
{
	CLIENT *clnt;
	char * *result_1;
	char *gettime_1_arg;
	intlist  *result_2;
	coupled_int_list  merge_1_arg;
	char * *result_3;
	char * reverse_1_arg;
	char  **result_4;
	char * readdir_1_arg;
	matrix  *result_5;
	coupled_matrix  addmatrix_1_arg;

    // user input
    char input[80];
    char c;
    int bytes_read;
    size_t nbytes = 100;
    char *my_string;


#ifndef	DEBUG
	clnt = clnt_create (host, CLOCKPROG, MYVERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

    // prompt 

    while(1){
            
        printf("1. datatime; 2. Merge 3. ReverseEcho; 4.ListFile 5.Add Matrix q: quit\n");
        my_string = (char *)malloc(nbytes +1);
        bytes_read = getline(&my_string,&nbytes, stdin);
        if(bytes_read == -1){
            puts("ERROR, now exit");
            exit(-1); 
        }
        c = my_string[0];
        printf("user input %c\n", c);

        // function 1 show the server time
        if(c == '1'){

            result_1 = gettime_1((void*)&gettime_1_arg, clnt);
            if (result_1 == (char **) NULL) {
                clnt_perror (clnt, "call failed");
            }
            else{
                // print the received time
                printf("time in server: %s\n", *result_1);
            }
        }

        // function 2 merge two lists
        else if (c == '2'){
            // prepare input
            int input_a[] = {1,2,3,4,5};
            int input_b[] = {2,4,5,6,7};

            int size_a = sizeof(input_a)/sizeof(int);
            int size_b = sizeof(input_b)/sizeof(int);

            // construct the list
            merge_1_arg.a = generate_list(input_a, size_a);
            merge_1_arg.b = generate_list(input_b, size_b);

            // print the input
            printf("list 1:\n\t");
            print_list(merge_1_arg.a);

            printf("list 2:\n\t");
            print_list(merge_1_arg.b);

            // remote call
            result_2 = merge_1(&merge_1_arg, clnt);
            if (result_2 == (intlist *) NULL) {
                clnt_perror (clnt, "call failed");
            }
            else{
                // print the merge result
                printf("after remote merge\n\t");
                print_list(*result_2);
            }
        }

        // function 3 reverse Echo
        else if(c == '3'){
            // ask for user input
            printf("please type a sentence\n");
            my_string = (char *)malloc(nbytes +1);
            bytes_read = getline(&my_string,&nbytes, stdin);
            if(bytes_read == -1){
                puts("ERROR, now exit");
                exit(-1); 
            }
            printf("string read: %s\n", my_string);

            reverse_1_arg = my_string;

            result_3 = reverse_1(&reverse_1_arg, clnt);
            if (result_3 == (char **) NULL) {
                clnt_perror (clnt, "call failed");
            }
            else{
                // print out the reversed string
                printf("after reverse: %s\n", *result_3);
            }

            free(my_string);
        }

        // function 4 list all files
        else if(c == '4'){

            printf("all the files under current directory:\n"); 

            char *input = ".";

            readdir_1_arg = input;
            result_4 = readdir_1((void*)&readdir_1_arg, clnt);
            if (result_4 == (char **) NULL) {
                clnt_perror (clnt, "call failed");
            }
            else{
                // print out the reversed string
                printf("\t%s", *result_4);
            }
        }

        // function 5 accept two integer matrix
        else if(c == '5'){
            //  prepare the two matrix
            int i, j;

            // input matrix
            int d1 = 2;
            int d2 = 3;
            int a[] = {1,2,3,4,5,6};
            int b[] = {1,2,3,4,5,6};

            // output matrix
            int *c;


            addmatrix_1_arg.a.data.data_len = d1*d2; 
            addmatrix_1_arg.a.data.data_val = a;
            addmatrix_1_arg.a.d1 = d1;
            addmatrix_1_arg.a.d2 = d2;

            addmatrix_1_arg.b.data.data_len = d1*d2; 
            addmatrix_1_arg.b.data.data_val = a;
            addmatrix_1_arg.b.d1 = d1;
            addmatrix_1_arg.b.d2 = d2;

            // save the arrays
            printf("\t matrix a:\n");
            print_matrix(a, d1, d2);

            printf("\t matrix b:\n");
            print_matrix(b, d1, d2);

            printf("array is mashalled\n");

            result_5 = addmatrix_1(&addmatrix_1_arg, clnt);

            if (result_5 == (matrix *) NULL) {
                clnt_perror (clnt, "call failed");
            }
            // else print the content of the matrix
            else{

                printf("\t result:\n");
                print_matrix(result_5->data.data_val, d1, d2);
            }
        }

        else if(c == 'q'){
            printf("bye\n");
            break;
        }

        else{
            printf("wrong input!\n");
        }
    }
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	clockprog_1 (host);
exit (0);
}
