/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "my_rpc.h"
#include <stdio.h>


void
clockprog_1(char *host)
{
	CLIENT *clnt;
	char * *result_1;
	char *gettime_1_arg;
	intlist  *result_2;
	coupled_int_list  merge_1_arg;
	char * *result_3;
	char * reverse_1_arg;
	char  **result_4;
	int  *result_5;
	coupled_matrix  addmatrix_1_arg;

    // user input
    char input[80];
    char c;
    int bytes_read;
    size_t nbytes = 100;
    char *my_string;


#ifndef	DEBUG
	clnt = clnt_create (host, CLOCKPROG, MYVERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

    // prompt 

    while(1){
            
        printf("1. datatime; 2. Merge 3. ReverseEcho; 4.ListFile 5.Add Matrix q: quit\n");
        my_string = (char *)malloc(nbytes +1);
        bytes_read = getline(&my_string,&nbytes, stdin);
        if(bytes_read == -1){
            puts("ERROR, now exit");
            exit(-1); 
        }
        c = my_string[0];
        printf("user input %c\n", c);

        // function 1 show the server time
        if(c == '1'){

            result_1 = gettime_1((void*)&gettime_1_arg, clnt);
            if (result_1 == (char **) NULL) {
                clnt_perror (clnt, "call failed");
            }
            else{
                // print the received time
                printf("time in server: %s\n", *result_1);
            }
        }

        // function 2 merge two lists
        else if (c == '2'){
            result_2 = merge_1(&merge_1_arg, clnt);
            if (result_2 == (intlist *) NULL) {
                clnt_perror (clnt, "call failed");
            }
        }

        // function 3 reverse Echo
        else if(c == '3'){
            // ask for user input
            printf("please type a sentence\n");
            my_string = (char *)malloc(nbytes +1);
            bytes_read = getline(&my_string,&nbytes, stdin);
            if(bytes_read == -1){
                puts("ERROR, now exit");
                exit(-1); 
            }
            printf("string read: %s\n", my_string);

            reverse_1_arg = my_string;

            result_3 = reverse_1(&reverse_1_arg, clnt);
            if (result_3 == (char **) NULL) {
                clnt_perror (clnt, "call failed");
            }
            else{
                // print out the reversed string
                printf("after reverse: %s\n", *result_3);
            }

            free(my_string);
        }

        // function 4 list all files
        else if(c == '4'){
           
            result_4 = readdir_1((void*)&gettime_1_arg, clnt);
            if (result_4 == (char **) NULL) {
                clnt_perror (clnt, "call failed");
            }
            else{
                // print out the reversed string
                printf("files in this directory\n: %s\n", *result_4);
            }
        }

        // function 5 accept two integer matrix
        else if(c == '5'){
            result_5 = addmatrix_1(&addmatrix_1_arg, clnt);
            if (result_5 == (int *) NULL) {
                clnt_perror (clnt, "call failed");
            }
        }

        else if(c == 'q'){
            printf("bye\n");
            break;
        }

        else{
            printf("wrong input!\n");
        }
    }
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	clockprog_1 (host);
exit (0);
}
