/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "my_rpc.h"
#include <time.h>

/* 
 * function 1 get the server time
 */
char **
gettime_1_svc(void *argp, struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */
    time_t thetime = time(0);
    result = ctime(&thetime);
    return &result;
}


/* 
 * function 2
 * merge two list
 */
intlist *
merge_1_svc(coupled_int_list *argp, struct svc_req *rqstp)
{
	static intlist  result;
    
	/*
	 * insert server code here
	 */

    /*
    result = NULL;

    intlist a = argp->a;
    intlist b = argp->b;

    intlist p;
    intlist tail = result;
    // try to merge two list
    while(p=a; p->next != NULL; p++){
        // get a new node
        intnode* tmp =  (intnode*)malloc(sizeof(intnode));
        tmp->next = NULL;
        if(result == NULL)

        

    }
    while
    */
        
	return &result;
}

/* 
 * function 3
 * reverse user input
 */
char **
reverse_1_svc(char **argp, struct svc_req *rqstp)
{
	static char * result;
    int i = 0;
    int length=0;

	/*
	 * insert server code here
	 */
    static char reversed[101];

    // get the length first
    while((*argp)[i]!='\n')
        i++;
    length = i;

    //now reverse
    for(i = 0; i< length; i++)
        reversed[i] = (*argp)[length -1 - i];

    reversed[i] = '\n';
    result = reversed;
	return &result;
}

/* 
 * function 4
 * read all the entries in a directory
 */
readdir_res *
readdir_1_svc(nametype *argp, struct svc_req *rqstp)
{
	static readdir_res  result;

	/*
	 * insert server code here
	 */

	return &result;
}


/*
 * function 5
 * add two matrix and return the integer sum
 */
int *
addmatrix_1_svc(coupled_matrix *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
    // get the dimension

	return &result;
}
